name: webserver  CI/CD
on:
  workflow_dispatch:

jobs:
    lint:
        name: Lint Ansible Playbook
        runs-on: ubuntu-latest

        steps:
        - name: Checkout
          uses: actions/checkout@v4.1.1
          
        - name: Ansible Linting Action
          uses: ansible-actions/ansible-lint-action@v1.0.2
          with:
            targets: |
              ansible/playbook.yml
              ansible/inventory

        
      
          



